### ISSUE TITLE
Erro ao rodar o servidor

### ISSUE THREAD

**Issue by emmanuellmota** [Qwizer/realmap11#10]
Boa tarde, quando tento colocar o servidor para rodar, acontece o seguinte erro:
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure> >'
  what():  failed opening file: No such file or directory
Aborted (core dumped)

Segue o log completo:
> The OTX Server and Forgotten Server Global - Version: (3.10)
Compiled with: GNU C++ version 4.8.4
Compiled on Dec 26 2018 16:30:44 for platform x64
>
> A server developed by Matt Gomez, Leandro Brewster, Erick Nunes, Joao Leonardo Pereira, Bruno Carvalho, Charles Kassab, OTX Contributors and The Forgotten Server Developers.
Visit our forum for updates, support, and resources: https://github.com/Qwizer/realmap11.
>
> Loading config: config.lua
> Establishing database connection... MySQL 5.5.62
> Running database manager
 Optimizing table account_ban_history... [success]
 Optimizing table account_bans... [success]
 Optimizing table account_viplist... [success]
 Optimizing table accounts... [success]
 Optimizing table blessings_history... [success]
 Optimizing table global_storage... [success]
 Optimizing table guild_invites... [success]
 Optimizing table guild_membership... [success]
 Optimizing table guild_ranks... [success]
 Optimizing table guild_wars... [success]
 Optimizing table guilds... [success]
 Optimizing table guildwar_kills... [success]
 Optimizing table house_lists... [success]
 Optimizing table houses... [success]
 Optimizing table ip_bans... [success]
 Optimizing table live_casts... [success]
 Optimizing table market_history... [success]
 Optimizing table market_offers... [success]
 Optimizing table player_deaths... [success]
 Optimizing table player_depotitems... [success]
 Optimizing table player_former_names... [success]
 Optimizing table player_inboxitems... [success]
 Optimizing table player_items... [success]
 Optimizing table player_kills... [success]
 Optimizing table player_misc... [success]
 Optimizing table player_namelocks... [success]
 Optimizing table player_prey... [success]
 Optimizing table player_preytimes... [success]
 Optimizing table player_rewards... [success]
 Optimizing table player_spells... [success]
 Optimizing table player_storage... [success]
 Optimizing table players... [success]
 Optimizing table sellchar... [success]
 Optimizing table server_config... [success]
 Optimizing table store_history... [success]
 Optimizing table tile_store... [success]
 Optimizing table z_forum... [success]
 Optimizing table z_ots_comunication... [success]
 Optimizing table z_shop_history_item... [success]
 Optimizing table z_shop_offer... [success]
> Loading vocations
> Loading items
> Loading script systems
> Loading monsters
> Loading outfits
> Checking world type... PVP
> Loading map
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure> >'
  what():  failed opening file: No such file or directory
Aborted (core dumped)

Estou tentando rodar em cima do Ubuntu 14.04.1
Quem puder ajudar, desde já eu agradeço!

**Comment by favasconcelos** [comment]
Verifica se o mapa está no local correto, dentro da pasta world. (Ao baixar o repositório, essa pasta está zipada dentro da pasta data).

**Comment by emmanuellmota** [comment]
@favasconcelos, funcionou, valew!
