### ISSUE TITLE
Erros ao abrir Server 

### ISSUE THREAD

**Issue by RuquanBR** [Qwizer/realmap11#4]
Falta de arquivos: 

[Warning - Event::checkScript] Can not load script: scripts/exercise_training.lua
cannot open data/actions/scripts/exercise_training.lua: No such file or directory

[Spawn::addMonster] Can not find Grand Canon Dominus
[Spawn::addMonster] Can not find Gelidrazah the Frozen

[Warning - Monsters::loadMonster] Unknown loot item "carrot on stick".
[Warning - Monsters::loadMonster] Cant load loot. data/monster/humanoids/Feyrist/pooka.xml

[Spawn::addMonster] Can not find Kroazur
[Spawn::addMonster] Can not find Dragon Servant
[Spawn::addMonster] Can not find Dragon Servant
[Spawn::addMonster] Can not find Dragon Wrath
[Spawn::addMonster] Can not find Dragon Wrath
[Spawn::addMonster] Can not find Dragon Wrath
[Spawn::addMonster] Can not find Dragon Wrath

**Comment by RuquanBR** [comment]
**[FIX]  [Spawn::addMonster] Can not find Grand Canon Dominus**

> Acesse: \data\monster\monsters.xml
> Adicionar a seguinte linha no arquivo monsters.xml

`New Line: 1170 <monster name="Grand Canon Dominus" file="falcons/Grand Canon Dominus.xml" />`

**Comment by RuquanBR** [comment]
**[FIX]  exercise_training**

> Acesse o diretório: \data\actions\scripts\
> Procure por **_exercise_training.lua.lua_**
> e Renomeie para **_"exercise_training.lua"_**

**Comment by RuquanBR** [comment]
**[FIX] [Spawn::addMonster] Can not find Gelidrazah the Frozen**

> Procure: data\monster\specialcreatures\bosses\Gelidrazah the Frozen.xml
> Mova para: \data\monster\places\FirstDragon\Gelidrazah the Frozen.xml

> Acesse: \data\monster\monsters.xml e adicione a seguinte linha: 
New Line: 11 
`<monster name="Gelidrazah the Frozen" file="places/FirstDragon/Gelidrazah the Frozen.xml" /> `

**Comment by RuquanBR** [comment]
**[FIX] 	[Warning - Monsters::loadMonster] Unknown loot item "carrot on stick".
[FIX] [Warning - Monsters::loadMonster] Cant load loot. data/monster/humanoids/Feyrist/pooka.xml**

Procure: data/monster/humanoids/Feyrist/pooka.xml

Localize a linha referente aos loots: 
```
DE: <item name="carrot on stick" chance="20" />
PARA: <item name="carrot on a stick" chance="20" />
```

**Comment by djblah** [comment]
Can you share me login.php 11.44
